In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [7]:
import sys

print(sys.executable)

c:\Users\Gaurav\AppData\Local\Programs\Python\Python313\python.exe

In [8]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\Gaurav\AppData\Local\Programs\Python\Python313\python.exe
3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]

In [9]:
%pip install pandas scikit-learn

Requirement already satisfied: pandas in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (3.0.5)
Requirement already satisfied: scikit-learn in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gaurav\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in c:\users\gaurav\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
## Loadd the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
## Preprocess the datqa
### Drop irrlevant columns
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [12]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [13]:
##Encode Categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [14]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [15]:
## Onehot encode 'Geography'
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [16]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [17]:
geo_encoder = onehot_encoder_geo.fit_transform(
    data[['Geography']]
).toarray()

geo_encoded_df = pd.DataFrame(
    geo_encoder,
    columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
)

In [18]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [19]:
## combine one hot encoder column with original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [20]:
## Save the encoders and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open("onehot_encoder_geo.pkl",'wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [21]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [22]:
## decide the dataset into independent and dependent features
X=data.drop('Exited',axis=1)
y=data['Exited']

##split data in training and testing sets

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [23]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Implementation

In [24]:
%pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\gaurav\appdata\roaming\python\python313\site-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (7.36.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\gaurav\appdata\roaming\python\python313\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\gaurav\appdata\roaming\python\python313\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.4.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.83.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.5.3)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\gaurav\appdata\roaming\python\python313\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [26]:
## Build our ANN model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),  ##1st hidden layer connected with input layer
    Dense(32,activation='relu'), ##2nd Hidden layer
    Dense(1,activation='sigmoid')  ## output layer
]

)

c:\Users\Gaurav\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [29]:
%pip install cuda

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement cuda (from versions: none)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for cuda

In [30]:
## compile the model
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [38]:
%pip install tensorboard

Collecting tensorboard
  Using cached tensorboard-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorboard) (1.83.1)
Collecting markdown>=2.6.8 (from tensorboard)
  Downloading markdown-3.10.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.12.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorboard) (2.5.3)
Requirement already satisfied: packaging in c:\users\gaurav\appdata\roaming\python\python313\site-packages (from tensorboard) (26.2)
Collecting pillow (from tensorboard)
  Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorboard) (7.36.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\gaurav\appdata\local\programs\python\python313\lib\site-packages (from tensorboard) (84.0.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard)
  Downloading werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\gaurav\appdata\roaming\python\python313\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Collecting markupsafe>=2.1.1 (from werkzeug>=1.0.1->tensorboard)
  Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Downloading tensorboard-2.21.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ------- -------------------------------- 1.0/5.5 MB 6.1 MB/s eta 0:00:01
   ----------------- ---------------------- 2.4/5.5 MB 6.1 MB/s eta 0:00:01
   -------------------------- ------------- 3.7/5.5 MB 6.0 MB/s eta 0:00:01
   ---------------------------------- ----- 4.7/5.5 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 5.5 MB/s eta 0:00:00
Using cached tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Downloading markdown-3.10.3-py3-none-any.whl (110 kB)
Downloading werkzeug-3.1.8-py3-none-any.whl (226 kB)
Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl (15 kB)
Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/7.2 MB 5.6 MB/s eta 0:00:02
   ----------- ---------------------------- 2.1/7.2 MB 5.7 MB/s eta 0:00:01
   ------------------ --------------------- 3.4/7.2 MB 5.8 MB/s eta 0:00:01
   -------------------------- ------------- 4.7/7.2 MB 5.8 MB/s eta 0:00:01
   --------------------------------- ------ 6.0/7.2 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 5.7 MB/s eta 0:00:00
Installing collected packages: tensorboard-data-server, pillow, markupsafe, markdown, werkzeug, tensorboard

   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   -------------------- ------------------- 3/6 [markdown]
   -------------------- ------------------- 3/6 [markdown]
   -------------------------- ------------- 4/6 [werkzeug]
   -------------------------- ------------- 4/6 [werkzeug]
   -------------------------- ------------- 4/6 [werkzeug]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   --------------------------------- ------ 5/6 [tensorboard]
   ---------------------------------------- 6/6 [tensorboard]

Successfully installed markdown-3.10.3 markupsafe-3.0.3 pillow-12.3.0 tensorboard-2.21.0 tensorboard-data-server-0.7.2 werkzeug-3.1.8
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script markdown_py.exe is installed in 'c:\Users\Gaurav\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tensorboard.exe is installed in 'c:\Users\Gaurav\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [32]:
## set up the TensorBoard
from  tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit" + datetime.datetime.now().strftime("%Y%m%D-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [34]:
## set up early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [39]:
## Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7980 - loss: 0.4522 - val_accuracy: 0.8385 - val_loss: 0.3878
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8446 - loss: 0.3783 - val_accuracy: 0.8550 - val_loss: 0.3582
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8561 - loss: 0.3523 - val_accuracy: 0.8595 - val_loss: 0.3437
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8571 - loss: 0.3437 - val_accuracy: 0.8630 - val_loss: 0.3401
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8599 - loss: 0.3379 - val_accuracy: 0.8600 - val_loss: 0.3430
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8593 - loss: 0.3337 - val_accuracy: 0.8655 - val_loss: 0.3404
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8612 - loss: 0.3307 - val_accuracy: 0.8625 - val_loss: 0.3433
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8650 - loss: 0.3290 - val_accuracy: 0.8700 - val_loss: 0.3375
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8649 - loss: 0.3253 - val_accuracy: 0.8655 - val_loss: 0.3427
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8658 - loss: 0.3246 - val_accuracy: 0.8665 - val_loss: 0.3383
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8674 - loss: 0.3229 - val_accuracy: 0.8690 - val_loss: 0.3394
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8643 - loss: 0.3216 - val_accuracy: 0.8665 - val_loss: 0.3358
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8684 - loss: 0.3187 - val_accuracy: 0.8665 - val_loss: 0.3395
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8668 - loss: 0.3177 - val_accuracy: 0.8660 - val_loss: 0.3371
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8684 - loss: 0.3171 - val_accuracy: 0.8630 - val_loss: 0.3389
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8691 - loss: 0.3150 - val_accuracy: 0.8660 - val_loss: 0.3381
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8671 - loss: 0.3147 - val_accuracy: 0.8625 - val_loss: 0.3404

In [40]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [41]:
## Load TEnsorboard Extension
%load_ext tensorboard

In [42]:
%tensorboard --logdir logs/fit

In [ ]:
## Load the pickle file